name: 'Hello World'
description: 'Greet someone using other actions'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Greet with an Action Package
      uses: immutable-actions/e2e-test-public-org-accessible-action@0.0.2
      with:
        who-to-greet: ${{ inputs.who-to-greet }}

    - name: Greet with an Action repo commit
      uses: immutable-actions/e2e-test-public-enterprise-accessible-action@main
      with:
        who-to-greet: ${{ inputs.who-to-greet }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

